%% setupProject.m — One-click project bootstrap for MATLAB Online
% =========================================================================
% Run this script ONCE in MATLAB Online to create the full project
% structure, all source files, tests, and Git configuration.
%
% Usage (paste into MATLAB Online Command Window):
%   >> setupProject
%
% What it does:
%   1. Creates folder structure (src/, tests/, data/, results/, docs/)
%   2. Writes all source functions into src/
%   3. Writes all test classes into tests/
%   4. Writes the main pipeline script
%   5. Writes Git config files (.gitignore, .gitattributes)
%   6. Writes documentation (README, CONTRIBUTING, LICENSE)
%   7. Writes GitHub Actions CI workflow
%   8. Configures the MATLAB path
%   9. Initialises a local Git repository
%
% After running, type "main" to execute the analysis pipeline.
% =========================================================================

fprintf('╔══════════════════════════════════════════════════════════╗\n');
fprintf('║   MATLAB + GitHub Demo — Project Setup (MATLAB Online)  ║\n');
fprintf('╚══════════════════════════════════════════════════════════╝\n\n');

%% ---- 1. Define the project root ----------------------------------------
projectRoot = fullfile(userpath, 'matlab-github-demo');
if ~exist(projectRoot, 'dir')
    mkdir(projectRoot);
end
cd(projectRoot);
fprintf('[✓] Project root: %s\n', projectRoot);

%% ---- 2. Create folder structure ----------------------------------------
folders = {'src', 'tests', 'data', 'results', 'docs', 'docs/images', ...
           '.github', '.github/workflows'};
for k = 1:numel(folders)
    d = fullfile(projectRoot, folders{k});
    if ~exist(d, 'dir'), mkdir(d); end
end
fprintf('[✓] Folder structure created\n');

%% ---- 3. Write source files ---------------------------------------------
writeSourceFiles(projectRoot);
fprintf('[✓] Source files written to src/\n');

%% ---- 4. Write test files -----------------------------------------------
writeTestFiles(projectRoot);
fprintf('[✓] Test files written to tests/\n');

%% ---- 5. Write main pipeline & helpers -----------------------------------
writeMainAndHelpers(projectRoot);
fprintf('[✓] main.m, startup.m, runAllTests.m written\n');

%% ---- 6. Write Git configuration ----------------------------------------
writeGitConfig(projectRoot);
fprintf('[✓] .gitignore, .gitattributes written\n');

%% ---- 7. Write documentation --------------------------------------------
writeDocs(projectRoot);
fprintf('[✓] README.md, CONTRIBUTING.md, LICENSE written\n');

%% ---- 8. Write CI workflow ----------------------------------------------
writeCIWorkflow(projectRoot);
fprintf('[✓] .github/workflows/ci.yml written\n');

%% ---- 9. Configure MATLAB path ------------------------------------------
addpath(fullfile(projectRoot, 'src'));
addpath(fullfile(projectRoot, 'tests'));
fprintf('[✓] MATLAB path configured\n');

%% ---- 10. Initialise Git repository -------------------------------------
fprintf('\n--- Git Initialisation ---\n');
prevDir = pwd;
cd(projectRoot);

[statusInit, resultInit] = system('git init');
if statusInit == 0
    fprintf('[✓] Git repository initialised\n');
    
    % Configure Git (won't overwrite if already set)
    system('git config user.email "you@example.com"');
    system('git config user.name "MATLAB Demo User"');
    
    % Stage everything
    [statusAdd, ~] = system('git add .');
    if statusAdd == 0
        fprintf('[✓] All files staged\n');
    end
    
    % Commit
    [statusCommit, resultCommit] = system('git commit -m "Initial commit: MATLAB + GitHub demo project"');
    if statusCommit == 0
        fprintf('[✓] Initial commit created\n');
    else
        fprintf('[!] Commit note: %s\n', strtrim(resultCommit));
    end
    
    % Rename branch to main
    system('git branch -M main');
    fprintf('[✓] Branch renamed to "main"\n');
else
    fprintf('[!] Git not available: %s\n', strtrim(resultInit));
    fprintf('    You can initialise Git later from the MATLAB Source Control UI.\n');
end

cd(prevDir);

%% ---- Done! --------------------------------------------------------------
fprintf('\n╔══════════════════════════════════════════════════════════╗\n');
fprintf('║                  Setup Complete! 🎉                      ║\n');
fprintf('╠══════════════════════════════════════════════════════════╣\n');
fprintf('║  Next steps:                                             ║\n');
fprintf('║    1. cd(''%s'')              ║\n', projectRoot);
fprintf('║    2. main           → run the analysis pipeline         ║\n');
fprintf('║    3. runAllTests    → run the test suite                ║\n');
fprintf('║    4. Connect to GitHub (see README.md)                  ║\n');
fprintf('╚══════════════════════════════════════════════════════════╝\n');


%% ========================================================================
%  LOCAL FUNCTIONS — file content generators
%  ========================================================================

function writeSourceFiles(root)
    % --- generateSignal.m ---
    fid = fopen(fullfile(root,'src','generateSignal.m'),'w');
    fprintf(fid, '%s', [ ...
        'function [t, cleanSignal, noisySignal] = generateSignal(fs, duration, freqs, noiseLevel)' newline ...
        '%%GENERATESIGNAL  Create a multi-frequency test signal with additive noise.' newline ...
        '%%' newline ...
        '%%   [t, cleanSignal, noisySignal] = GENERATESIGNAL(fs, duration, freqs, noiseLevel)' newline ...
        '%%' newline ...
        '%%   Inputs' newline ...
        '%%   ------' newline ...
        '%%   fs         - Sampling frequency (Hz)' newline ...
        '%%   duration   - Signal length (seconds)' newline ...
        '%%   freqs      - Vector of sine-wave frequencies to superimpose (Hz)' newline ...
        '%%   noiseLevel - Standard deviation of Gaussian noise (default: 0.1)' newline ...
        '%%' newline ...
        '%%   Outputs' newline ...
        '%%   -------' newline ...
        '%%   t           - Time vector  (1 x N)' newline ...
        '%%   cleanSignal - Sum-of-sines without noise  (1 x N)' newline ...
        '%%   noisySignal - cleanSignal + Gaussian noise (1 x N)' newline ...
        newline ...
        '    arguments' newline ...
        '        fs         (1,1) double {mustBePositive}' newline ...
        '        duration   (1,1) double {mustBePositive}' newline ...
        '        freqs      (1,:) double {mustBePositive}' newline ...
        '        noiseLevel (1,1) double {mustBeNonnegative} = 0.1' newline ...
        '    end' newline ...
        newline ...
        '    t = 0 : 1/fs : duration - 1/fs;' newline ...
        '    cleanSignal = zeros(size(t));' newline ...
        '    for f = freqs' newline ...
        '        cleanSignal = cleanSignal + sin(2 * pi * f * t);' newline ...
        '    end' newline ...
        '    rng(42, ''twister'');' newline ...
        '    noisySignal = cleanSignal + noiseLevel * randn(size(t));' newline ...
        'end' newline]);
    fclose(fid);

    % --- analyseSignal.m ---
    fid = fopen(fullfile(root,'src','analyseSignal.m'),'w');
    fprintf(fid, '%s', [ ...
        'function results = analyseSignal(t, signal, fs)' newline ...
        '%%ANALYSESIGNAL  Perform spectral and statistical analysis on a 1-D signal.' newline ...
        '%%' newline ...
        '%%   results = ANALYSESIGNAL(t, signal, fs)' newline ...
        newline ...
        '    arguments' newline ...
        '        t      (1,:) double' newline ...
        '        signal (1,:) double' newline ...
        '        fs     (1,1) double {mustBePositive}' newline ...
        '    end' newline ...
        newline ...
        '    N = length(signal);' newline ...
        '    Y = fft(signal);' newline ...
        '    P2 = abs(Y / N);' newline ...
        '    P1 = P2(1 : floor(N/2) + 1);' newline ...
        '    P1(2:end-1) = 2 * P1(2:end-1);' newline ...
        '    freq = fs * (0 : floor(N/2)) / N;' newline ...
        newline ...
        '    results.freq          = freq;' newline ...
        '    results.powerSpectrum = P1;' newline ...
        newline ...
        '    [pks, locs] = findpeaks(P1, freq, ...' newline ...
        '        ''MinPeakHeight'',    max(P1) * 0.1, ...' newline ...
        '        ''MinPeakDistance'',   2);' newline ...
        '    results.peakFreqs  = locs;' newline ...
        '    results.peakPowers = pks;' newline ...
        newline ...
        '    results.meanVal = mean(signal);' newline ...
        '    results.stdVal  = std(signal);' newline ...
        '    results.rmsVal  = rms(signal);' newline ...
        '    results.maxVal  = max(signal);' newline ...
        '    results.minVal  = min(signal);' newline ...
        newline ...
        '    signalPower = sum(pks.^2);' newline ...
        '    totalPower  = sum(P1.^2);' newline ...
        '    noisePower  = totalPower - signalPower;' newline ...
        '    if noisePower > 0' newline ...
        '        results.snrEstimate = 10 * log10(signalPower / noisePower);' newline ...
        '    else' newline ...
        '        results.snrEstimate = Inf;' newline ...
        '    end' newline ...
        'end' newline]);
    fclose(fid);

    % --- visualiseResults.m ---
    fid = fopen(fullfile(root,'src','visualiseResults.m'),'w');
    fprintf(fid, '%s', [ ...
        'function figHandles = visualiseResults(t, cleanSignal, noisySignal, results, config)' newline ...
        '%%VISUALISERESULTS  Create publication-quality plots from the analysis.' newline ...
        newline ...
        '    figHandles = gobjects(1, 3);' newline ...
        newline ...
        '    %% Figure 1 : Time-domain signals' newline ...
        '    figHandles(1) = figure(''Name'', ''TimeDomain'', ''Position'', [100 100 900 400]);' newline ...
        '    subplot(2,1,1);' newline ...
        '    plot(t, cleanSignal, ''b'', ''LineWidth'', 1.2);' newline ...
        '    title(''Clean Signal (no noise)'');' newline ...
        '    xlabel(''Time (s)''); ylabel(''Amplitude'');' newline ...
        '    grid on;' newline ...
        '    subplot(2,1,2);' newline ...
        '    plot(t, noisySignal, ''Color'', [0.8 0.2 0.2], ''LineWidth'', 0.6);' newline ...
        '    title(sprintf(''Noisy Signal (\\\\sigma = %.2f)'', config.noiseLevel));' newline ...
        '    xlabel(''Time (s)''); ylabel(''Amplitude'');' newline ...
        '    grid on;' newline ...
        '    sgtitle(''Time-Domain View'', ''FontWeight'', ''bold'');' newline ...
        newline ...
        '    %% Figure 2 : Frequency spectrum' newline ...
        '    figHandles(2) = figure(''Name'', ''FrequencySpectrum'', ''Position'', [100 550 900 400]);' newline ...
        '    stem(results.freq, results.powerSpectrum, ''b'', ''MarkerSize'', 3);' newline ...
        '    hold on;' newline ...
        '    plot(results.peakFreqs, results.peakPowers, ''rv'', ''MarkerSize'', 10, ''MarkerFaceColor'', ''r'');' newline ...
        '    hold off;' newline ...
        '    xlim([0 max(config.signalFreq) * 2]);' newline ...
        '    title(''Single-Sided Amplitude Spectrum'');' newline ...
        '    xlabel(''Frequency (Hz)''); ylabel(''|P1(f)|'');' newline ...
        '    legend(''Spectrum'', ''Detected Peaks'', ''Location'', ''northeast'');' newline ...
        '    grid on;' newline ...
        '    for k = 1:numel(results.peakFreqs)' newline ...
        '        text(results.peakFreqs(k), results.peakPowers(k) * 1.08, ...' newline ...
        '            sprintf(''%.1f Hz'', results.peakFreqs(k)), ...' newline ...
        '            ''HorizontalAlignment'', ''center'', ''FontSize'', 9, ''Color'', ''r'');' newline ...
        '    end' newline ...
        newline ...
        '    %% Figure 3 : Statistics summary' newline ...
        '    figHandles(3) = figure(''Name'', ''StatsSummary'', ''Position'', [100 1000 500 350]);' newline ...
        '    statLabels = {''Mean'', ''Std Dev'', ''RMS'', ''Max'', ''Min'', ''SNR (dB)''};' newline ...
        '    statValues = [results.meanVal, results.stdVal, results.rmsVal, ...' newline ...
        '                  results.maxVal,  results.minVal, results.snrEstimate];' newline ...
        '    barh(statValues, ''FaceColor'', [0.2 0.6 0.8]);' newline ...
        '    set(gca, ''YTick'', 1:numel(statLabels), ''YTickLabel'', statLabels);' newline ...
        '    xlabel(''Value'');' newline ...
        '    title(''Signal Statistics'');' newline ...
        '    grid on;' newline ...
        'end' newline]);
    fclose(fid);

    % --- generateReport.m ---
    fid = fopen(fullfile(root,'src','generateReport.m'),'w');
    fprintf(fid, '%s', [ ...
        'function generateReport(results, config, outputPath)' newline ...
        '%%GENERATEREPORT  Write a plain-text summary report to disk.' newline ...
        newline ...
        '    fid = fopen(outputPath, ''w'');' newline ...
        '    if fid == -1' newline ...
        '        error(''generateReport:fileOpen'', ''Cannot open %s for writing.'', outputPath);' newline ...
        '    end' newline ...
        '    cleanUp = onCleanup(@() fclose(fid));' newline ...
        newline ...
        '    fprintf(fid, ''==================================================\\n'');' newline ...
        '    fprintf(fid, ''  MATLAB + GitHub Demo - Analysis Summary Report\\n'');' newline ...
        '    fprintf(fid, ''  Generated: %s\\n'', datestr(now, ''yyyy-mm-dd HH:MM:SS''));' newline ...
        '    fprintf(fid, ''==================================================\\n\\n'');' newline ...
        newline ...
        '    fprintf(fid, ''--- Configuration ---\\n'');' newline ...
        '    fprintf(fid, ''Sample Rate   : %d Hz\\n'', config.sampleRate);' newline ...
        '    fprintf(fid, ''Duration      : %.1f s\\n'', config.duration);' newline ...
        '    fprintf(fid, ''Signal Freqs  : %s Hz\\n'', mat2str(config.signalFreq));' newline ...
        '    fprintf(fid, ''Noise Level   : %.2f\\n\\n'', config.noiseLevel);' newline ...
        newline ...
        '    fprintf(fid, ''--- Detected Peaks ---\\n'');' newline ...
        '    for k = 1:numel(results.peakFreqs)' newline ...
        '        fprintf(fid, ''  Peak %d : %.2f Hz  (power = %.4f)\\n'', ...' newline ...
        '            k, results.peakFreqs(k), results.peakPowers(k));' newline ...
        '    end' newline ...
        '    fprintf(fid, ''\\n--- Statistics ---\\n'');' newline ...
        '    fprintf(fid, ''Mean          : %.6f\\n'', results.meanVal);' newline ...
        '    fprintf(fid, ''Std Dev       : %.6f\\n'', results.stdVal);' newline ...
        '    fprintf(fid, ''RMS           : %.6f\\n'', results.rmsVal);' newline ...
        '    fprintf(fid, ''Max           : %.6f\\n'', results.maxVal);' newline ...
        '    fprintf(fid, ''Min           : %.6f\\n'', results.minVal);' newline ...
        '    fprintf(fid, ''SNR Estimate  : %.2f dB\\n\\n'', results.snrEstimate);' newline ...
        '    fprintf(fid, ''==================================================\\n'');' newline ...
        '    fprintf(fid, ''  End of Report\\n'');' newline ...
        '    fprintf(fid, ''==================================================\\n'');' newline ...
        'end' newline]);
    fclose(fid);
end


function writeTestFiles(root)
    % --- TestGenerateSignal.m ---
    fid = fopen(fullfile(root,'tests','TestGenerateSignal.m'),'w');
    fprintf(fid, '%s', [ ...
        'classdef TestGenerateSignal < matlab.unittest.TestCase' newline ...
        '    properties (TestParameter)' newline ...
        '        Frequency = {5, 20, 100}' newline ...
        '    end' newline ...
        '    methods (Test)' newline ...
        '        function testOutputSizes(testCase)' newline ...
        '            [t, c, n] = generateSignal(500, 1, [10], 0.1);' newline ...
        '            testCase.verifyEqual(numel(t), numel(c));' newline ...
        '            testCase.verifyEqual(numel(t), numel(n));' newline ...
        '        end' newline ...
        '        function testCorrectNumberOfSamples(testCase)' newline ...
        '            fs = 1000; dur = 2;' newline ...
        '            [t, ~, ~] = generateSignal(fs, dur, [5], 0);' newline ...
        '            testCase.verifyEqual(numel(t), fs * dur);' newline ...
        '        end' newline ...
        '        function testZeroNoise(testCase)' newline ...
        '            [~, c, n] = generateSignal(1000, 1, [10 20], 0);' newline ...
        '            testCase.verifyEqual(c, n, ''AbsTol'', 1e-12);' newline ...
        '        end' newline ...
        '        function testPeakFrequencyDetected(testCase, Frequency)' newline ...
        '            fs = 1000; dur = 2;' newline ...
        '            [~, ~, sig] = generateSignal(fs, dur, Frequency, 0);' newline ...
        '            Y = fft(sig);' newline ...
        '            N = numel(sig);' newline ...
        '            P = abs(Y(1:floor(N/2)+1) / N);' newline ...
        '            P(2:end-1) = 2 * P(2:end-1);' newline ...
        '            freqAxis = fs * (0:floor(N/2)) / N;' newline ...
        '            [~, idx] = max(P);' newline ...
        '            testCase.verifyEqual(freqAxis(idx), Frequency, ''AbsTol'', 1);' newline ...
        '        end' newline ...
        '        function testReproducibility(testCase)' newline ...
        '            [~, ~, n1] = generateSignal(1000, 1, [10], 0.5);' newline ...
        '            [~, ~, n2] = generateSignal(1000, 1, [10], 0.5);' newline ...
        '            testCase.verifyEqual(n1, n2);' newline ...
        '        end' newline ...
        '    end' newline ...
        'end' newline]);
    fclose(fid);

    % --- TestAnalyseSignal.m ---
    fid = fopen(fullfile(root,'tests','TestAnalyseSignal.m'),'w');
    fprintf(fid, '%s', [ ...
        'classdef TestAnalyseSignal < matlab.unittest.TestCase' newline ...
        '    methods (Test)' newline ...
        '        function testOutputIsStruct(testCase)' newline ...
        '            [t, ~, sig] = generateSignal(1000, 1, [10], 0.1);' newline ...
        '            res = analyseSignal(t, sig, 1000);' newline ...
        '            testCase.verifyClass(res, ''struct'');' newline ...
        '        end' newline ...
        '        function testRequiredFieldsExist(testCase)' newline ...
        '            [t, ~, sig] = generateSignal(1000, 1, [10], 0.1);' newline ...
        '            res = analyseSignal(t, sig, 1000);' newline ...
        '            expectedFields = {''freq'',''powerSpectrum'',''peakFreqs'',''peakPowers'', ...' newline ...
        '                              ''meanVal'',''stdVal'',''rmsVal'',''maxVal'',''minVal'',''snrEstimate''};' newline ...
        '            for k = 1:numel(expectedFields)' newline ...
        '                testCase.verifyTrue(isfield(res, expectedFields{k}));' newline ...
        '            end' newline ...
        '        end' newline ...
        '        function testPeakDetectionAccuracy(testCase)' newline ...
        '            targetFreqs = [10 25];' newline ...
        '            [t, ~, sig] = generateSignal(1000, 2, targetFreqs, 0);' newline ...
        '            res = analyseSignal(t, sig, 1000);' newline ...
        '            for f = targetFreqs' newline ...
        '                testCase.verifyTrue(any(abs(res.peakFreqs - f) < 1.5));' newline ...
        '            end' newline ...
        '        end' newline ...
        '        function testRmsPositive(testCase)' newline ...
        '            [t, ~, sig] = generateSignal(1000, 1, [10], 0.2);' newline ...
        '            res = analyseSignal(t, sig, 1000);' newline ...
        '            testCase.verifyGreaterThan(res.rmsVal, 0);' newline ...
        '        end' newline ...
        '        function testSnrFiniteForCleanSignal(testCase)' newline ...
        '            [t, ~, sig] = generateSignal(1000, 1, [10], 0);' newline ...
        '            res = analyseSignal(t, sig, 1000);' newline ...
        '            testCase.verifyTrue(res.snrEstimate > 0 || isinf(res.snrEstimate));' newline ...
        '        end' newline ...
        '    end' newline ...
        'end' newline]);
    fclose(fid);
end


function writeMainAndHelpers(root)
    % --- main.m ---
    fid = fopen(fullfile(root,'main.m'),'w');
    fprintf(fid, '%s', [ ...
        '%%%% MATLAB + GitHub Demo Project - Main Entry Point' newline ...
        'clear; clc; close all;' newline ...
        newline ...
        '%% Configuration' newline ...
        'config.sampleRate   = 1000;' newline ...
        'config.duration     = 2;' newline ...
        'config.noiseLevel   = 0.3;' newline ...
        'config.signalFreq   = [5, 12, 30];' newline ...
        'config.outputDir    = fullfile(pwd, ''results'');' newline ...
        'config.dataDir      = fullfile(pwd, ''data'');' newline ...
        newline ...
        'fprintf(''=== MATLAB + GitHub Demo Pipeline ===\\n'');' newline ...
        'fprintf(''Sample Rate  : %d Hz\\n'', config.sampleRate);' newline ...
        'fprintf(''Duration     : %.1f s\\n'', config.duration);' newline ...
        'fprintf(''Signal Freqs : %s Hz\\n'', mat2str(config.signalFreq));' newline ...
        'fprintf(''Noise Level  : %.2f\\n\\n'', config.noiseLevel);' newline ...
        newline ...
        '%% Step 1 : Generate synthetic data' newline ...
        'fprintf(''[1/4] Generating synthetic data...\\n'');' newline ...
        '[t, cleanSignal, noisySignal] = generateSignal( ...' newline ...
        '    config.sampleRate, config.duration, ...' newline ...
        '    config.signalFreq, config.noiseLevel);' newline ...
        'save(fullfile(config.dataDir, ''raw_signal.mat''), ...' newline ...
        '     ''t'', ''cleanSignal'', ''noisySignal'', ''config'');' newline ...
        'fprintf(''      Saved -> data/raw_signal.mat\\n'');' newline ...
        newline ...
        '%% Step 2 : Analyse the signal' newline ...
        'fprintf(''[2/4] Running analysis...\\n'');' newline ...
        'analysisResults = analyseSignal(t, noisySignal, config.sampleRate);' newline ...
        newline ...
        '%% Step 3 : Visualise' newline ...
        'fprintf(''[3/4] Generating plots...\\n'');' newline ...
        'figHandles = visualiseResults(t, cleanSignal, noisySignal, analysisResults, config);' newline ...
        'for k = 1:numel(figHandles)' newline ...
        '    figName = get(figHandles(k), ''Name'');' newline ...
        '    safeName = matlab.lang.makeValidName(figName);' newline ...
        '    exportgraphics(figHandles(k), ...' newline ...
        '        fullfile(config.outputDir, [safeName ''.png'']), ''Resolution'', 150);' newline ...
        '    fprintf(''      Exported -> results/%s.png\\n'', safeName);' newline ...
        'end' newline ...
        newline ...
        '%% Step 4 : Save results' newline ...
        'fprintf(''[4/4] Saving results...\\n'');' newline ...
        'save(fullfile(config.outputDir, ''analysis_results.mat''), ''analysisResults'');' newline ...
        'fprintf(''      Saved -> results/analysis_results.mat\\n'');' newline ...
        'reportPath = fullfile(config.outputDir, ''summary_report.txt'');' newline ...
        'generateReport(analysisResults, config, reportPath);' newline ...
        'fprintf(''      Report -> results/summary_report.txt\\n'');' newline ...
        'fprintf(''\\n=== Pipeline complete ===\\n'');' newline]);
    fclose(fid);

    % --- startup.m ---
    fid = fopen(fullfile(root,'startup.m'),'w');
    fprintf(fid, '%s', [ ...
        'function startup()' newline ...
        '%%STARTUP  Project bootstrap - runs automatically when MATLAB opens this folder.' newline ...
        '    projectRoot = fileparts(mfilename(''fullpath''));' newline ...
        '    addpath(fullfile(projectRoot, ''src''));' newline ...
        '    dirs = {''results'', ''data''};' newline ...
        '    for k = 1:numel(dirs)' newline ...
        '        d = fullfile(projectRoot, dirs{k});' newline ...
        '        if ~exist(d, ''dir''), mkdir(d); end' newline ...
        '    end' newline ...
        '    fprintf(''MATLAB-GitHub-Demo project loaded.\\n'');' newline ...
        '    fprintf(''  Project root : %s\\n'', projectRoot);' newline ...
        '    fprintf(''  Type "main" to run the full pipeline.\\n\\n'');' newline ...
        'end' newline]);
    fclose(fid);

    % --- runAllTests.m ---
    fid = fopen(fullfile(root,'runAllTests.m'),'w');
    fprintf(fid, '%s', [ ...
        '%%%% runAllTests.m - Execute the full test suite' newline ...
        'import matlab.unittest.TestSuite' newline ...
        'import matlab.unittest.TestRunner' newline ...
        'fprintf(''=== Running Test Suite ===\\n\\n'');' newline ...
        'addpath(fullfile(pwd, ''src''));' newline ...
        'addpath(fullfile(pwd, ''tests''));' newline ...
        'suite = TestSuite.fromFolder(''tests'');' newline ...
        'runner = TestRunner.withTextOutput(''Verbosity'', 3);' newline ...
        'results = runner.run(suite);' newline ...
        'fprintf(''\\n=== Test Summary ===\\n'');' newline ...
        'fprintf(''Total : %d\\n'', numel(results));' newline ...
        'fprintf(''Passed: %d\\n'', sum([results.Passed]));' newline ...
        'fprintf(''Failed: %d\\n'', sum([results.Failed]));' newline ...
        'if any([results.Failed])' newline ...
        '    fprintf(2, ''\\n** SOME TESTS FAILED **\\n'');' newline ...
        'else' newline ...
        '    fprintf(''\\nAll tests passed.\\n'');' newline ...
        'end' newline]);
    fclose(fid);
end


function writeGitConfig(root)
    % --- .gitignore ---
    fid = fopen(fullfile(root,'.gitignore'),'w');
    fprintf(fid, '%s', [ ...
        '# MATLAB auto-generated files' newline ...
        '*.asv' newline ...
        '*.m~' newline ...
        '*.mex*' newline ...
        'slprj/' newline ...
        '*.slxc' newline ...
        newline ...
        '# Build & output artifacts' newline ...
        'codegen/' newline ...
        'results/*.mat' newline ...
        'results/*.png' newline ...
        'results/*.txt' newline ...
        'data/*.mat' newline ...
        newline ...
        '# OS files' newline ...
        '.DS_Store' newline ...
        'Thumbs.db' newline ...
        'Desktop.ini' newline ...
        newline ...
        '# Editor temp files' newline ...
        '*.swp' newline ...
        '*~' newline ...
        '.vscode/' newline ...
        newline ...
        '# Logs' newline ...
        '*.log' newline ...
        'tmp/' newline]);
    fclose(fid);

    % --- .gitattributes ---
    fid = fopen(fullfile(root,'.gitattributes'),'w');
    fprintf(fid, '%s', [ ...
        '*.m        text diff=matlab' newline ...
        '*.mlx      binary' newline ...
        '*.mat      binary' newline ...
        '*.fig      binary' newline ...
        '*.slx      binary' newline ...
        '*.p        binary' newline ...
        '*.md       text diff=markdown' newline ...
        '*.txt      text' newline ...
        '*.yml      text' newline ...
        '*.yaml     text' newline ...
        '*.png      binary' newline ...
        '*.jpg      binary' newline]);
    fclose(fid);
end


function writeDocs(root)
    % --- README.md (abbreviated version — full doc is already in place) ---
    fid = fopen(fullfile(root,'README.md'),'w');
    fprintf(fid, '%s', [ ...
        '# MATLAB + GitHub Demo Project' newline ...
        newline ...
        '> A turnkey demonstration of how to use **MATLAB Online** in a professional, ' newline ...
        'version-controlled workflow with **Git & GitHub**.' newline ...
        newline ...
        '## Quick Start (MATLAB Online)' newline ...
        newline ...
        '```matlab' newline ...
        '%% 1. Run the setup script (creates everything)' newline ...
        '>> setupProject' newline ...
        newline ...
        '%% 2. Navigate to the project' newline ...
        '>> cd(fullfile(userpath, ''matlab-github-demo''))' newline ...
        newline ...
        '%% 3. Run the pipeline' newline ...
        '>> main' newline ...
        newline ...
        '%% 4. Run all tests' newline ...
        '>> runAllTests' newline ...
        '```' newline ...
        newline ...
        '## Project Structure' newline ...
        '```' newline ...
        'matlab-github-demo/' newline ...
        '  main.m              % Entry point' newline ...
        '  startup.m           % Auto-path configuration' newline ...
        '  runAllTests.m       % Test runner' newline ...
        '  setupProject.m      % One-click project setup' newline ...
        '  gitHelper.m         % Git commands from MATLAB' newline ...
        '  src/' newline ...
        '    generateSignal.m' newline ...
        '    analyseSignal.m' newline ...
        '    visualiseResults.m' newline ...
        '    generateReport.m' newline ...
        '  tests/' newline ...
        '    TestGenerateSignal.m' newline ...
        '    TestAnalyseSignal.m' newline ...
        '  data/               % Generated data (git-ignored)' newline ...
        '  results/             % Output figures & reports (git-ignored)' newline ...
        '```' newline ...
        newline ...
        '## Git & GitHub from MATLAB Online' newline ...
        newline ...
        'Use the built-in **Source Control** panel or run `gitHelper` commands:' newline ...
        newline ...
        '```matlab' newline ...
        'gitHelper status          %% See changed files' newline ...
        'gitHelper add             %% Stage all changes' newline ...
        'gitHelper commit "msg"    %% Commit with message' newline ...
        'gitHelper push            %% Push to GitHub' newline ...
        'gitHelper log             %% View commit history' newline ...
        '```' newline ...
        newline ...
        '### Connect to GitHub (first time)' newline ...
        newline ...
        '1. Create a repo on [github.com](https://github.com/new) named `matlab-github-demo`' newline ...
        '2. In MATLAB Online:' newline ...
        '```matlab' newline ...
        'gitHelper setremote "https://github.com/YOUR-USERNAME/matlab-github-demo.git"' newline ...
        'gitHelper push' newline ...
        '```' newline ...
        newline ...
        '## Running Tests' newline ...
        '```matlab' newline ...
        '>> runAllTests' newline ...
        '```' newline ...
        newline ...
        '## License' newline ...
        'MIT License - see [LICENSE](LICENSE)' newline]);
    fclose(fid);

    % --- CONTRIBUTING.md ---
    fid = fopen(fullfile(root,'CONTRIBUTING.md'),'w');
    fprintf(fid, '%s', [ ...
        '# Contributing' newline ...
        newline ...
        '1. Fork the repo on GitHub' newline ...
        '2. Clone or open in MATLAB Online' newline ...
        '3. Create a feature branch: `git checkout -b feature/my-change`' newline ...
        '4. Make changes, run `runAllTests`' newline ...
        '5. Commit and push' newline ...
        '6. Open a Pull Request on GitHub' newline ...
        newline ...
        '## Code Style' newline ...
        '- camelCase for functions and variables' newline ...
        '- Every function needs a help block' newline ...
        '- Use argument validation blocks' newline ...
        '- Tests must pass before committing' newline]);
    fclose(fid);

    % --- LICENSE ---
    fid = fopen(fullfile(root,'LICENSE'),'w');
    fprintf(fid, '%s', [ ...
        'MIT License' newline ...
        newline ...
        'Copyright (c) 2026 Ayac' newline ...
        newline ...
        'Permission is hereby granted, free of charge, to any person obtaining a copy' newline ...
        'of this software and associated documentation files (the "Software"), to deal' newline ...
        'in the Software without restriction, including without limitation the rights' newline ...
        'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell' newline ...
        'copies of the Software, and to permit persons to whom the Software is' newline ...
        'furnished to do so, subject to the following conditions:' newline ...
        newline ...
        'The above copyright notice and this permission notice shall be included in all' newline ...
        'copies or substantial portions of the Software.' newline ...
        newline ...
        'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.' newline]);
    fclose(fid);
end


function writeCIWorkflow(root)
    fid = fopen(fullfile(root,'.github','workflows','ci.yml'),'w');
    fprintf(fid, '%s', [ ...
        'name: MATLAB CI' newline ...
        'on:' newline ...
        '  push:' newline ...
        '    branches: [main]' newline ...
        '  pull_request:' newline ...
        '    branches: [main]' newline ...
        'jobs:' newline ...
        '  test:' newline ...
        '    runs-on: ubuntu-latest' newline ...
        '    steps:' newline ...
        '      - uses: actions/checkout@v4' newline ...
        '      - uses: matlab-actions/setup-matlab@v2' newline ...
        '      - uses: matlab-actions/run-tests@v2' newline ...
        '        with:' newline ...
        '          source-folder: src' newline ...
        '          test-results-junit: results/test-results.xml' newline]);
    fclose(fid);
end
